[conditional_trips]
trip_types = ["battery_swap", "idling_sherpa"]

[conditional_trips.idling_sherpa]
book=false
max_trips = 2
threshold = 600
priority = 1

[conditional_trips.battery_swap]
book=false
max_trips = 2
threshold = 15
priority = 10
