[fleet.comms]
mule_heartbeat_interval=60

[fleet.simulator]
simulate=false
book_trips=false

[optimal_dispatch]
method="hungarian"
prioritise_waiting_stations=true
eta_power_factor=1.0
priority_power_factor=0.5

[fleet]
mode="default"
handler_package="handlers.default.handlers"
handler_class="Handlers"
sherpa_port="5000"
server_ip=""
fleet_names=[]
customer=""
site=""
location=""

[docker_registry]
port=443

[frontenduser.<user>]
hashed_password=""

[external_connections.<connection_name>]
fleet_names=[]
hashed_password=""

[fleet_sherpas.<sherpa_name>]
hwid=""
api_key=""
fleet_name=""
vehicle_type=""
