[fleet.comms]
mule_heartbeat_interval=60

[fleet.simulator]
simulate=false
book_trips=false

[fleet]
mode="default"
handler_package="handlers.default.handlers"
handler_class="Handlers"
sherpa_port="5000"
server_ip=""
fleet_names=[]
customer=""
site=""
location=""

[frontenduser.<user>]
hashed_password=""

[fleet_sherpas.<sherpa_name>]
hwid=""
api_key=""
fleet_name=""
