[fleet]
mode="default"
handler_package="handlers.default.handlers"
handler_class="Handlers"
sherpa_port=""
fleet_names = []
customer = ""
site = ""
location = ""

[rq.jobs]
http_retry_attempts = 3

[fleet.comms]
mule_heartbeat_interval = 60

[fleet_sherpas.<sherpa_name>]
hwid=""
api_key=""
fleet_name=""

~                   
