[fleet.comms]
mule_heartbeat_interval=60

[frontenduser.admin]
hashed_password="03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"

[docker_registry]
port=443

[fleet.simulator]
simulate=false
book_trips=false

[optimal_dispatch]
method="hungarian"
prioritise_waiting_stations=true
eta_power_factor=1.0
priority_power_factor=0.5

[fleet]
mode="default"
handler_package="handlers.default.handlers"
handler_class="Handlers"
sherpa_port="5000"
server_ip=""
fleet_names=[" "]
customer=" "
site=" "
location=" "

[fleet_sherpas.<sherpa_name>]
hwid=" "
api_key=""
fleet_name=""

