[fleet.comms]
mule_heartbeat_interval=60

[alerts]
notifications=true
slack_webhook_url="https://hooks.slack.com/services/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"
time_interval=20

[fleet.rq]
default_job_timeout = 15
generic_handler_job_timeout = 10

[optimal_dispatch]
method="hungarian"
prioritise_waiting_stations=true
eta_power_factor=1.0
priority_power_factor=0.1

[fleet.stations]
dispatch_timeout=10.0

[fleet.simulator]
simulate=false
book_trips=false
visa_handling=false
speedup_factor=1.0
average_velocity=0.8

[fleet]
mode="default"
handler_package="handlers.default.handlers"
handler_class="Handlers"
sherpa_port="5000"
http_scheme="https"

[fleet.simulator.routes]
#route1 = [["Station A", "Station B"], [10]]]

[fleet.simulator.initialize_sherpas_at]
#sample_sherpa="Station A"

