[fleet]
mode="default"
handler_package="handlers.default.handlers"
handler_class="Handlers"
sherpa_port="5000"
server_ip=""
fleet_names=["TVS-Hosur-3wheeler-Line", "TVS-Hosur-3wheeler-Empty-trolly-Line"]
customer="TVS Motor"
site="Hosur"
location="3 wheeler"

[fleet_sherpas.tug-24-tvsmotor-hosur-05]
hwid="T30-383HGC"
api_key="mserIFsprXNw-YAMbApslCMqJ6JgJlJvQeVt6IwKE9c_T30-383HGC"
fleet_name="TVS-Hosur-3wheeler-Line"

[fleet_sherpas.tug-23-tvsmotor-hosur-03]
hwid="T30-789PAI"
api_key="qZhoteD9zOHn_wBoYW04vgeaiLSBIoWP_jaVy5TQLp0_T30-789PAI"
fleet_name="TVS-Hosur-3wheeler-Empty-trolly-Line"

[rq.jobs]
http_retry_attempts=3

[fleet.comms]
mule_heartbeat_interval=60

[frontenduser.admin]
hashed_password="03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"

