[frontenduser.admin]
hashed_password="03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
role="operator"

[frontenduser.operator]
hashed_password="5a9b1a4e1af2ba1e0feb61942fce91600191981ad2b943b2fcc1ca48e2176e6c"
role="operator"

[frontenduser.supervisor]
hashed_password="2b91a2428e9a45865347252761b31aaadb88f544df72caa5ca27b8cc665bc06e"
role="supervisor"

[frontenduser.ati_support]
hashed_password="c2191e2515f6b527564b08dc0a67af4dfc3bcf1f2df134e3e79f5c96e0bc313c"
role="support"