[master_fm]
mfm_ip="15.206.242.52"
mfm_port="443"
mfm_cert_file="/app/master_fm_comms/aws_master_cert.pem"
http_scheme="https"
ws_scheme="wss"
ws_suffix="ws/api/v1/master_fm/fm_client"

[master_fm.comms]
ws_update_freq=60
update_freq=120
api_key=""
