[master_fm]
mfm_ip="192.168.10.27"
mfm_port="5001"
mfm_cert_file=""
http_scheme="http"
ws_scheme="ws"
ws_suffix="ws/api/v1/master_fm/fm_client"

[master_fm.comms]
ws_update_freq=30
update_freq=60
api_key="p"
