[master_fm]
mfm_ip="sanjaya.atimotors.com"
mfm_port="443"
mfm_cert_file="/etc/ssl/certs/ca-certificates.crt"
http_scheme="https"
ws_scheme="wss"
ws_suffix="ws/api/v1/master_fm/fm_client"

[master_fm.comms]
send_updates=false
ws_update_freq=60
update_freq=120
api_key=""
