[master_fm]
mfm_ip="127.0.0.1"
mfm_port="9010"
mfm_cert_file="/etc/ssl/certs/ca-certificates.crt"
http_scheme="http"
ws_scheme="ws"
ws_suffix="ws/api/v1/master_fm/fm_client"

[master_fm.comms]
send_updates=false
ws_update_freq=60
update_freq=120
api_key=""
