services:
  fm_container:
    image: fleet_manager
    restart: always
    build: .
    ports:
      - $FM_PORT:$FM_PORT
    volumes:
      - ~/fleet_manager/logs:/logs
      - ~/fleet_manager/static:/static
      - ~/fleet_manager/static/config:/app/mule/config
      - /tmp:/tmp
    depends_on:
      - psql_container

  psql_container:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - $PSQL_PORT:5432
    volumes:
      - ~/fleet_manager/static/db:/var/lib/postgresql/data
