services:
  fm_container:
    image: fleet_manager
    restart: always
    build: .
    ports:
      - '8002:8002'
    volumes:
      - ~/fleet_manager/logs:/app/logs
      - ~/fleet_manager/static:/static
      - ~/fleet_manager/static/config:/app/mule/config
      - /tmp:/tmp
    depends_on:
      - psql_container
      - redis_container
  redis_container:
    image: redis
    ports:
      - '6370:6379'
    volumes:
      - ~/fleet_manager/static/redis:/data   
  psql_container:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5400:5432'
    volumes:
      - ~/fleet_manager/static/db:/var/lib/postgresql/data
