services:
  manager:
    image: fleet_manager
    restart: always
    build: .
    ports:
      - '8002:8002'
    volumes:
      - ~/fleet_manager/logs:/app/logs
      - ~/fleet_manager/static:/static  
      - /tmp:/tmp
    environment:
      PGHOST: psql_container 
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    links:
      - db
    depends_on:
      - db
    network_mode: bridge

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/fleet_manager/static/db:/var/lib/postgresql/data
    network_mode: bridge
